### PR TITLE
Keep raw value if it has not been parsed

### LINKED ISSUE #13: Parentheses "()" are being removed from table values
```cucumber
Given the existing table "some_table":
  | some_column |
  | foo (bar)   |
When the resulting table "some_table" is queried
Then the result exactly matches:
  | some_column |
  | foo (bar)   |
```
This fails with error:
```
Does not match exactly, got:
| some_column |
| foo         |
(RuntimeError)
./features/test.feature:1:in `Then the result exactly matches:'
```

Values with parentheses are just stripped from the table data.

### PR DESCRIPTION
**Pull request by moertel**
Whenever a value with parentheses would be encountered, the match groups
would be removed from the resulting string. This does not make sense as
the only case we're interested in a parsed value is when we're dealing
with date placeholders. This commit fixes the issue by returning the
original value if no date conversion has taken place.

Fixes #13

### CODE REVIEW

**Comment by moertel** [comment]
@IanSchweer I'm both annoyed and relieved that two hours of debugging resulted in changing one line of code. Oh well!

File: lib/squcumber-postgres/support/matchers.rb [hunk 1]
```diff
@@ -138,7 +138,7 @@ def convert_mock_value(value)
 
       formatted_new_value.to_s
     else
-      new_value.to_s
```
Comment (IanSchweer) [inline lib/squcumber-postgres/support/matchers.rb]: <3
